device_type: network
models:
- id: 21f8ff6a-3be8-4eee-9285-df11aac1686b
  code: cisco-c9300
  name: Cisco Catalyst 9300
  vendor: Cisco
  model: Catalyst 9300
  default_height_u: 1
  tags:
  - switch
- id: 847c3e5c-5b76-4c8a-994e-66009ddf7f0c
  code: fortigate-100f
  name: Fortinet FortiGate 100F
  vendor: Fortinet
  model: FortiGate 100F
  default_height_u: 1
  tags:
  - firewall
  - edge
- id: d2d2d2d2-0001-4d2d-d2d2-d2d2d2d2d201
  code: cisco-asr1001x
  name: Cisco ASR 1001-X
  vendor: Cisco
  model: ASR 1001-X
  default_height_u: 1
  tags:
  - router
  - edge
- id: d2d2d2d2-0002-4d2d-d2d2-d2d2d2d2d202
  code: patch-panel-24p
  name: Patch Panel 24-port
  default_height_u: 1
  tags:
  - patch-panel
  - cabling
