device_type: rack_object

models:
  - id: 2b65592a-18b8-41c7-9a27-1f03aa631e4f
    code: blank-panel-1u
    name: Zaślepka 1U
    default_height_u: 1
    tags:
      - blank-panel

  - id: c3cb54dd-f0d8-4594-96a1-d27f59c7f3ee
    code: cable-organizer-1u
    name: Organizer kabli 1U
    default_height_u: 1
    tags:
      - cable-management

  - id: 7ff43b2f-18e0-4522-b170-ea1c8a4e28c5
    code: reserved-space
    name: Zarezerwowane miejsce
    default_height_u: 1
    tags:
      - reservation

  - id: 9d2b25b4-28e8-4e56-a6a0-42f4a682b216
    code: unknown-object
    name: Nieopisany element / zajęte miejsce
    default_height_u: 1
    tags:
      - unknown
