import { existsSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { basename, join } from "node:path";

const SENTINEL = "ownership-sentinel";
const PREFIX = "ris-wdio-";

/**
 * Create an isolated temporary environment for the WDIO suite and set the
 * necessary environment variables before any Tauri process is launched.
 *
 * Call this at module-load time in wdio.conf.ts (before the config export)
 * so the env vars are inherited by the WDIO launcher, workers, tauri-driver,
 * and the Tauri binary.
 *
 * Returns a cleanup function. Register it in the WDIO `onComplete` hook.
 * Cleanup is skipped when RIS_E2E_KEEP_TEMP=1 is set.
 *
 * Safety guards applied before any deletion:
 *   - path must be under os.tmpdir()
 *   - basename must start with "ris-wdio-"
 *   - ownership sentinel must be present
 */
export function initTestEnvironment(): () => void {
  // WDIO workers inherit env vars from the launcher and also load wdio.conf.ts.
  // If RIS_E2E_REPOSITORY_PARENT is already set, initialization already happened
  // in the launcher process — skip and return a no-op so workers do not create
  // redundant temp dirs.
  if (process.env["RIS_E2E_REPOSITORY_PARENT"]) {
    return () => {};
  }

  const runRoot = mkdtempSync(join(tmpdir(), PREFIX));

  // Write sentinel before any other work so guards can fire even on partial setup.
  writeFileSync(join(runRoot, SENTINEL), "ris-wdio-test-environment\n");

  const appConfig = join(runRoot, "app-config");
  const appData = join(runRoot, "app-data");
  const appCache = join(runRoot, "app-cache");
  const gitDir = join(runRoot, "git");
  const repoParent = join(runRoot, "repositories");

  for (const dir of [appConfig, appData, appCache, gitDir, repoParent]) {
    mkdirSync(dir, { recursive: true });
  }

  // Minimal git identity so `git init` + any initial commit does not fail.
  const gitConfig = join(gitDir, "config");
  writeFileSync(
    gitConfig,
    "[user]\n\tname = Rack Inventory Studio E2E\n\temail = e2e@localhost.invalid\n",
  );

  // Linux XDG dirs — isolate WebKit localStorage and Tauri app data.
  process.env["XDG_CONFIG_HOME"] = appConfig;
  process.env["XDG_DATA_HOME"] = appData;
  process.env["XDG_CACHE_HOME"] = appCache;

  // Windows equivalents (no-op on Linux; harmless to set).
  process.env["APPDATA"] = appData;
  process.env["LOCALAPPDATA"] = join(runRoot, "app-local-data");

  // Git isolation — never touch the real global config.
  process.env["GIT_CONFIG_GLOBAL"] = gitConfig;
  process.env["GIT_CONFIG_NOSYSTEM"] = "1";

  // Expose repository parent path to specs.
  process.env["RIS_E2E_REPOSITORY_PARENT"] = repoParent;

  console.log(`[test-environment] run root: ${runRoot}`);

  return () => {
    cleanup(runRoot);
  };
}

function cleanup(runRoot: string): void {
  if (process.env["RIS_E2E_KEEP_TEMP"] === "1") {
    console.log(`[test-environment] RIS_E2E_KEEP_TEMP=1 — preserved: ${runRoot}`);
    return;
  }

  // Guard: must be under the system temp directory.
  if (!runRoot.startsWith(tmpdir())) {
    console.error(`[test-environment] safety guard: path is not under tmpdir(), refusing to delete: ${runRoot}`);
    return;
  }

  // Guard: basename must carry the expected prefix (auto-generated by mkdtempSync).
  if (!basename(runRoot).startsWith(PREFIX)) {
    console.error(`[test-environment] safety guard: basename does not start with '${PREFIX}', refusing: ${runRoot}`);
    return;
  }

  // Guard: ownership sentinel must be present.
  if (!existsSync(join(runRoot, SENTINEL))) {
    console.error(`[test-environment] safety guard: sentinel not found, refusing to delete: ${runRoot}`);
    return;
  }

  rmSync(runRoot, { recursive: true, force: true });
  console.log(`[test-environment] cleaned up: ${runRoot}`);
}
