use std::fs;
use std::path::Path;

fn main() {
    // Register tauri-plugin-wdio's ACL manifest only when the wdio-plugin
    // feature is active; remove the generated file otherwise so a regular
    // build never tries to resolve it.
    //
    // The generated file is gitignored to keep the working tree clean between
    // feature and non-feature builds.
    let wdio_plugin_cap_path = Path::new("capabilities/wdio-plugin-test.json");

    if std::env::var("CARGO_FEATURE_WDIO_PLUGIN").is_ok() {
        let content = r#"{
  "$schema": "../gen/schemas/desktop-schema.json",
  "identifier": "wdio-plugin-test",
  "description": "Capability for the wdio-plugin test binary. Generated by build.rs — do not edit.",
  "windows": ["main"],
  "permissions": [
    "wdio:default"
  ]
}
"#;
        fs::write(wdio_plugin_cap_path, content)
            .expect("failed to write capabilities/wdio-plugin-test.json");
    } else if wdio_plugin_cap_path.exists() {
        fs::remove_file(wdio_plugin_cap_path)
            .expect("failed to remove stale capabilities/wdio-plugin-test.json");
    }

    tauri_build::build();
}
