use std::fs;
use std::path::Path;

fn main() {
    // When the wdio-embedded feature is active, create a capability file that
    // registers the embedded WebDriver plugin's ACL manifest with Tauri.
    // When the feature is inactive, remove the file so the regular build does
    // not try to resolve the permission (which would fail without the plugin).
    //
    // The generated file is gitignored to keep the working tree clean between
    // feature and non-feature builds.
    let cap_path = Path::new("capabilities/embedded-test.json");

    if std::env::var("CARGO_FEATURE_WDIO_EMBEDDED").is_ok() {
        // wdio-webdriver:default grants no IPC surface — the plugin is an in-process
        // HTTP server — but listing it ensures Tauri loads the plugin's ACL manifest.
        let content = r#"{
  "$schema": "../gen/schemas/desktop-schema.json",
  "identifier": "embedded-test",
  "description": "Capability for the wdio-embedded test binary. Generated by build.rs — do not edit.",
  "windows": ["main"],
  "permissions": [
    "wdio-webdriver:default"
  ]
}
"#;
        fs::write(cap_path, content).expect("failed to write capabilities/embedded-test.json");
    } else if cap_path.exists() {
        fs::remove_file(cap_path).expect("failed to remove stale capabilities/embedded-test.json");
    }

    // Same pattern for the wdio-plugin feature: register tauri-plugin-wdio's
    // ACL manifest only when the feature is active; remove the generated
    // file otherwise so a regular build never tries to resolve it.
    let wdio_plugin_cap_path = Path::new("capabilities/wdio-plugin-test.json");

    if std::env::var("CARGO_FEATURE_WDIO_PLUGIN").is_ok() {
        let content = r#"{
  "$schema": "../gen/schemas/desktop-schema.json",
  "identifier": "wdio-plugin-test",
  "description": "Capability for the wdio-plugin test binary. Generated by build.rs — do not edit.",
  "windows": ["main"],
  "permissions": [
    "wdio:default"
  ]
}
"#;
        fs::write(wdio_plugin_cap_path, content)
            .expect("failed to write capabilities/wdio-plugin-test.json");
    } else if wdio_plugin_cap_path.exists() {
        fs::remove_file(wdio_plugin_cap_path)
            .expect("failed to remove stale capabilities/wdio-plugin-test.json");
    }

    tauri_build::build();
}
