import { describe, it, expect } from "vitest";
import { escapeXml, sanitizeFilename, buildRackViewSvg } from "./rackExport";
import type { PlacementDto } from "../../api/tauriClient";

// ── escapeXml ─────────────────────────────────────────────────────────────────

describe("escapeXml", () => {
  it("escapes < and > to prevent tag injection", () => {
    expect(escapeXml("<script>alert(1)</script>")).toBe(
      "&lt;script&gt;alert(1)&lt;/script&gt;",
    );
  });

  it("escapes & to &amp;", () => {
    expect(escapeXml("Rack & Roll")).toBe("Rack &amp; Roll");
  });

  it("escapes double quote", () => {
    expect(escapeXml('He said "hello"')).toBe("He said &quot;hello&quot;");
  });

  it("escapes single quote", () => {
    expect(escapeXml("it's fine")).toBe("it&#39;s fine");
  });

  it("leaves safe text unchanged", () => {
    expect(escapeXml("My-Rack_01")).toBe("My-Rack_01");
  });
});

// ── sanitizeFilename ──────────────────────────────────────────────────────────

describe("sanitizeFilename", () => {
  it("replaces spaces with hyphens", () => {
    expect(sanitizeFilename("My Rack")).toBe("my-rack");
  });

  it("removes forbidden characters <:>|\\/\"?*", () => {
    const result = sanitizeFilename('rack<name>:"path"|?*.txt');
    expect(result).not.toMatch(/[<>:"/\\|?*]/);
  });

  it("lowercases the name", () => {
    expect(sanitizeFilename("RACK-A1")).toBe("rack-a1");
  });

  it("returns 'rack' for empty input", () => {
    expect(sanitizeFilename("")).toBe("rack");
  });

  it("returns 'rack' for input that reduces to empty after sanitization", () => {
    expect(sanitizeFilename("***")).toBe("rack");
  });

  it("strips leading and trailing hyphens/dots", () => {
    const result = sanitizeFilename("  --rack--  ");
    expect(result).not.toMatch(/^[-.]|[-.]$/);
  });
});

// ── Fixtures ──────────────────────────────────────────────────────────────────

function makePlacement(overrides: Partial<PlacementDto> = {}): PlacementDto {
  return {
    id: "plc-1",
    code: "plc-1",
    target_kind: "device",
    target_id: "dev-1",
    target_code: "SRV-001",
    target_name: "Web Server 01",
    device_type: "server",
    start_u: 1,
    height_u: 1,
    effective_height_u: 1,
    end_u: 1,
    note: null,
    tags: [],
    model_name: "Dell R640",
    model_code: "R640",
    target_serial: "SN12345",
    target_asset_tag: "AT-001",
    ...overrides,
  };
}

// ── buildRackViewSvg — structure ──────────────────────────────────────────────

describe("buildRackViewSvg — document structure", () => {
  it("produces a valid SVG root element", () => {
    const svg = buildRackViewSvg({
      rackName: "DC-A Rack 01",
      rackCode: "RACK-01",
      heightU: 4,
      side: "front",
      placements: [],
    });
    expect(svg).toContain('<svg xmlns="http://www.w3.org/2000/svg"');
    expect(svg).toContain("</svg>");
  });

  it("includes the rack name in the SVG", () => {
    const svg = buildRackViewSvg({
      rackName: "My Test Rack",
      rackCode: "TST-01",
      heightU: 2,
      side: "front",
      placements: [],
    });
    expect(svg).toContain("My Test Rack");
  });

  it("includes the rack code in the SVG", () => {
    const svg = buildRackViewSvg({
      rackName: "Rack",
      rackCode: "RACK-XYZ",
      heightU: 2,
      side: "front",
      placements: [],
    });
    expect(svg).toContain("RACK-XYZ");
  });

  it("includes 'Front' label when side is front", () => {
    const svg = buildRackViewSvg({
      rackName: "R",
      rackCode: "R1",
      heightU: 2,
      side: "front",
      placements: [],
    });
    expect(svg).toContain("Front");
  });

  it("includes 'Rear' label when side is rear", () => {
    const svg = buildRackViewSvg({
      rackName: "R",
      rackCode: "R1",
      heightU: 2,
      side: "rear",
      placements: [],
    });
    expect(svg).toContain("Rear");
  });

  it("includes the 'Generated by Rack Inventory Studio' footer", () => {
    const svg = buildRackViewSvg({
      rackName: "R",
      rackCode: "R1",
      heightU: 2,
      side: "front",
      placements: [],
    });
    expect(svg).toContain("Generated by Rack Inventory Studio");
  });
});

// ── buildRackViewSvg — placement content ─────────────────────────────────────

describe("buildRackViewSvg — placement content", () => {
  it("includes the placement device name", () => {
    const svg = buildRackViewSvg({
      rackName: "R",
      rackCode: "R1",
      heightU: 4,
      side: "front",
      placements: [makePlacement({ target_name: "My Device" })],
    });
    expect(svg).toContain("My Device");
  });

  it("includes the model name", () => {
    const svg = buildRackViewSvg({
      rackName: "R",
      rackCode: "R1",
      heightU: 4,
      side: "front",
      placements: [makePlacement({ model_name: "Dell R640" })],
    });
    expect(svg).toContain("Dell R640");
  });

  it("includes the serial number", () => {
    const svg = buildRackViewSvg({
      rackName: "R",
      rackCode: "R1",
      heightU: 4,
      side: "front",
      placements: [makePlacement({ target_serial: "SN-XYZ-999" })],
    });
    expect(svg).toContain("SN-XYZ-999");
  });

  it("includes U range for single-U placement", () => {
    const svg = buildRackViewSvg({
      rackName: "R",
      rackCode: "R1",
      heightU: 4,
      side: "front",
      placements: [makePlacement({ start_u: 3, effective_height_u: 1, end_u: 3 })],
    });
    expect(svg).toContain("U3");
  });

  it("includes U range for multi-U placement", () => {
    const svg = buildRackViewSvg({
      rackName: "R",
      rackCode: "R1",
      heightU: 6,
      side: "front",
      placements: [
        makePlacement({ start_u: 2, height_u: 3, effective_height_u: 3, end_u: 4 }),
      ],
    });
    expect(svg).toContain("U2");
    expect(svg).toContain("U4");
  });

  it("uses 'Unnamed device' fallback when target_name is null", () => {
    const svg = buildRackViewSvg({
      rackName: "R",
      rackCode: "R1",
      heightU: 4,
      side: "front",
      placements: [makePlacement({ target_name: null })],
    });
    expect(svg).toContain("Unnamed device");
  });

  it("uses 'Unnamed object' fallback for rack_object with no name", () => {
    const svg = buildRackViewSvg({
      rackName: "R",
      rackCode: "R1",
      heightU: 4,
      side: "front",
      placements: [makePlacement({ target_kind: "rack_object", target_name: null, model_name: null })],
    });
    expect(svg).toContain("Unnamed object");
  });
});

// ── buildRackViewSvg — XSS / XML injection ───────────────────────────────────

describe("buildRackViewSvg — XSS prevention", () => {
  it("does not emit raw <script> tag when device name contains script injection", () => {
    const svg = buildRackViewSvg({
      rackName: "R",
      rackCode: "R1",
      heightU: 4,
      side: "front",
      placements: [
        makePlacement({ target_name: "<script>alert(1)</script>" }),
      ],
    });
    expect(svg).not.toContain("<script>");
    expect(svg).not.toContain("</script>");
    expect(svg).toContain("&lt;script&gt;");
  });

  it("does not emit raw tags from rack name injection", () => {
    const svg = buildRackViewSvg({
      rackName: '<img src=x onerror="alert(1)">',
      rackCode: "R1",
      heightU: 2,
      side: "front",
      placements: [],
    });
    expect(svg).not.toContain("<img");
    expect(svg).toContain("&lt;img");
  });

  it("does not emit raw tags from rack code injection", () => {
    const svg = buildRackViewSvg({
      rackName: "R",
      rackCode: "</text><script>evil()</script>",
      heightU: 2,
      side: "front",
      placements: [],
    });
    expect(svg).not.toContain("<script>evil()");
  });
});

// ── buildRackViewSvg — front/rear isolation ───────────────────────────────────

describe("buildRackViewSvg — front/rear data isolation", () => {
  const frontOnly = makePlacement({ id: "f1", target_name: "Front Device" });
  const rearOnly = makePlacement({ id: "r1", target_name: "Rear Device" });

  it("front export includes only the front placements passed in", () => {
    const svg = buildRackViewSvg({
      rackName: "R",
      rackCode: "R1",
      heightU: 4,
      side: "front",
      placements: [frontOnly],
    });
    expect(svg).toContain("Front Device");
    expect(svg).not.toContain("Rear Device");
  });

  it("rear export includes only the rear placements passed in", () => {
    const svg = buildRackViewSvg({
      rackName: "R",
      rackCode: "R1",
      heightU: 4,
      side: "rear",
      placements: [rearOnly],
    });
    expect(svg).toContain("Rear Device");
    expect(svg).not.toContain("Front Device");
  });
});

// ── buildRackViewSvg — deterministic sort ────────────────────────────────────

describe("buildRackViewSvg — deterministic placement sort", () => {
  it("placement at higher U appears before placement at lower U in SVG output", () => {
    const p_low = makePlacement({ id: "p1", target_name: "Low-U Device", start_u: 1, effective_height_u: 1, end_u: 1 });
    const p_high = makePlacement({ id: "p2", target_name: "High-U Device", start_u: 4, effective_height_u: 1, end_u: 4 });

    const svg = buildRackViewSvg({
      rackName: "R",
      rackCode: "R1",
      heightU: 6,
      side: "front",
      placements: [p_low, p_high],
    });

    const idxHigh = svg.indexOf("High-U Device");
    const idxLow = svg.indexOf("Low-U Device");
    expect(idxHigh).toBeGreaterThan(-1);
    expect(idxLow).toBeGreaterThan(-1);
    // High-U device appears earlier in the SVG (visual top = higher U number)
    expect(idxHigh).toBeLessThan(idxLow);
  });

  it("produces identical SVG regardless of input order", () => {
    const p1 = makePlacement({ id: "p1", target_name: "Alpha", start_u: 3, effective_height_u: 1, end_u: 3 });
    const p2 = makePlacement({ id: "p2", target_name: "Beta", start_u: 1, effective_height_u: 1, end_u: 1 });

    const base: Omit<Parameters<typeof buildRackViewSvg>[0], "placements"> = {
      rackName: "R", rackCode: "R1", heightU: 6, side: "front",
    };

    const svgA = buildRackViewSvg({ ...base, placements: [p1, p2] });
    const svgB = buildRackViewSvg({ ...base, placements: [p2, p1] });
    expect(svgA).toBe(svgB);
  });
});
