[package]
name = "ris-application"
version = "0.1.0"
edition = "2021"
description = "Application use cases."

[dependencies]
ris-core = { path = "../ris-core" }
ris-repository = { path = "../ris-repository" }
ris-validation = { path = "../ris-validation" }
ris-import = { path = "../ris-import" }
uuid = { version = "1", features = ["v4"] }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
thiserror = "1"

[dev-dependencies]
tempfile = "3"
ris-git = { path = "../ris-git" }

